name: aoc-2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - matplotlib==3.9.2
  - pip==24.3.1
  - numpy==2.1.0
  - networkx==3.4.2
  - regex==2024.11.6
  - pandas==2.2.3
  - polars==1.15.0
  - pip:
    - advent-of-code-data==2.0.4
